import { Inter } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import "./styles/globals.css";

import Navbar from '@/app/components/Navbar'
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
const Josif = Josefin_Sans({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Josif.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
